### ISSUE TITLE
Not compatible with .Net Core 3.0

### ISSUE THREAD

**Issue by dimitridaras** [Cimpress-MCP/Tiger-HAL#21]
When adding to a .Net Core 3.0 project, I get the following error on build:

`Could not load type 'Microsoft.AspNetCore.Mvc.Formatters.JsonOutputFormatter' from assembly 'Microsoft.AspNetCore.Mvc.Formatters.Json, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.`

This is caused by `MvcJsonOptions` being removed from .Net Core 3.0 
https://stackoverflow.com/questions/58362757/could-not-load-type-microsoft-aspnetcore-mvc-mvcjsonoptions-from-assembly-mi

**Comment by chrisoverzero** [comment]
This is correct; the project is not yet compatible with .NET Core 3.x. It will take a lot of time and effort to make the transition due to the foundations of JSON support's having changed in 3.x. I'm not sure whether this library will stick with Newtonsoft.JSON or try to convert to the new libraries.

It's still on the roadmap either way!

**Comment by chrisoverzero** [comment]
This has reached `develop`, and release will come within a week.

**Comment by chrisoverzero** [comment]
This was released some time ago, and I failed to update the thread. I hope it's working well for you.
